# This is a basic workflow to help you get started with Actions

name: Build Android APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" , "develop"]
  pull_request:
    branches: [ "main" , "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
         distribution: 'zulu'
         java-version: '17'

      # Install Android SDK tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
         api-level: 30
         build-tools: 30.0.3

      - name: Debug Build Process
        run: |
          echo "Checking if Gradle ran successfully..."
          ls -R app/build || true


      - name: Debug APK Path
        run: |
         echo "Checking APK output directory..."
         ls -R app/build/outputs/apk/

      # Create the project (APK compilation)
      - name: Build APK
        run: ./gradlew clean assembleRelease

      - name: List Build Outputs
        run: |
         echo "Listing app/build directory..."
         ls -R app/build

      # Install APK as Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release.apk

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
